// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgCH3qXk3Rg3_WyUxj4uZLPJro16F0gZE',
    appId: '1:477090182078:web:2d4087d767948aee467fef',
    messagingSenderId: '477090182078',
    projectId: 'authentication-5479e',
    authDomain: 'authentication-5479e.firebaseapp.com',
    storageBucket: 'authentication-5479e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiNjN4-oNkN3rej-WUVXGxfYOTcwgrHr0',
    appId: '1:477090182078:android:e3ae67287ff74f29467fef',
    messagingSenderId: '477090182078',
    projectId: 'authentication-5479e',
    storageBucket: 'authentication-5479e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsP1hzNSqwJ3e0TZht1rfv3sF4zvnD6uc',
    appId: '1:477090182078:ios:07c97bada3d61370467fef',
    messagingSenderId: '477090182078',
    projectId: 'authentication-5479e',
    storageBucket: 'authentication-5479e.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsP1hzNSqwJ3e0TZht1rfv3sF4zvnD6uc',
    appId: '1:477090182078:ios:f80ac54279ebc9c1467fef',
    messagingSenderId: '477090182078',
    projectId: 'authentication-5479e',
    storageBucket: 'authentication-5479e.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase.RunnerTests',
  );
}
